title: João Pedro Gomes dos Santos
description: Computational Neuroscience PhD | Scientific Software Developer
author: João Pedro Gomes dos Santos
email: jpgs.12390@gmail.com
baseurl: ""
url: "https://jpgsantos.github.io"

# Social links
github_username: jpgsantos
linkedin_username: joaosantos1992

# Open Graph / Social Sharing
og_image: /assets/images/og-share.png
twitter:
  card: summary_large_image

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Navigation
header_pages:
  - index.md
  - about.md
  - projects.md
  - cv.md
  - contact.md

# Custom variables
location: "Copenhagen, Amsterdam or Remote"
position: "Computational Neuroscience PhD | Scientific Software Developer"
available: true